apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Settings__Jwt__ExpirationTimeMinutes: "1000"
  Settings__IdCryptographyAlphabet: "peKcMZ1lrFsDOdA2Rxj9H85Bohw6aGJNvITgQf403ntSqkXmUVWyiCLu7PzYEb"