apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  ConnectionStrings__Connection: "Server=192.168.0.78,1433;Database=EsperancaSolidariaIdentity;User Id=hackathon;Password=Hackathon@123;TrustServerCertificate=true"
  Settings__Jwt__SigningKey: "K2|A_-C271TP}{3Gy0r[#{5*mOzjncbf"